# Generated by Django 4.2.7 on 2023-11-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='LOST', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
